name: Main

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: main-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 23]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v5
        with:
          pnpm-version: 10.8.0
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: pnpm -r build

      - name: Lint
        run: pnpm -r lint

      - name: Test
        run: pnpm -r test
