name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: publish-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v5
        with:
          pnpm-version: 10.8.0
          node-version: 22

      - name: Publish to npm
        working-directory: packages/mcp-auth
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
